
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.x_road.emta_v6;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2018-09-26T02:51:27.698+03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "webService",
                      portName = "port",
                      targetNamespace = "http://emta-v6.x-road.eu",
                      wsdlLocation = "classpath:services.wsdl",
                      endpointInterface = "eu.x_road.emta_v6.WebServiceInterface")
                      
public class PortImpl implements WebServiceInterface {

    private static final Logger LOG = Logger.getLogger(PortImpl.class.getName());

    /* (non-Javadoc)
     * @see eu.x_road.emta_v6.WebServiceInterface#xteeFieAndmed(eu.x_road.emta_v6.PersonalIdentityCode keha, eu.x_road.xsd.identifiers.XRoadClientIdentifierType client, eu.x_road.xsd.identifiers.XRoadServiceIdentifierType service, java.lang.String id, java.lang.String protocolVersion, java.lang.String userId, java.lang.String issue, eu.x_road.emta_v6.PersonalIdentityCode paring, eu.x_road.emta_v6.XteeFieAndmedResponseType keha1, eu.x_road.xsd.identifiers.XRoadClientIdentifierType client1, eu.x_road.xsd.identifiers.XRoadServiceIdentifierType service1, java.lang.String id1, java.lang.String protocolVersion1, java.lang.String userId1, java.lang.String issue1)*
     */
    public void xteeFieAndmed(eu.x_road.emta_v6.PersonalIdentityCode keha, eu.x_road.xsd.identifiers.XRoadClientIdentifierType client, eu.x_road.xsd.identifiers.XRoadServiceIdentifierType service, java.lang.String id, java.lang.String protocolVersion, java.lang.String userId, java.lang.String issue, javax.xml.ws.Holder<PersonalIdentityCode> paring, javax.xml.ws.Holder<XteeFieAndmedResponseType> keha1, javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadClientIdentifierType> client1, javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadServiceIdentifierType> service1, javax.xml.ws.Holder<java.lang.String> id1, javax.xml.ws.Holder<java.lang.String> protocolVersion1, javax.xml.ws.Holder<java.lang.String> userId1, javax.xml.ws.Holder<java.lang.String> issue1) { 
        LOG.info("Executing operation xteeFieAndmed");
        System.out.println(keha);
        System.out.println(client);
        System.out.println(service);
        System.out.println(id);
        System.out.println(protocolVersion);
        System.out.println(userId);
        System.out.println(issue);
        try {
            eu.x_road.emta_v6.PersonalIdentityCode paringValue = null;
            paring.value = paringValue;
            eu.x_road.emta_v6.XteeFieAndmedResponseType keha1Value = null;
            keha1.value = keha1Value;
            eu.x_road.xsd.identifiers.XRoadClientIdentifierType client1Value = null;
            client1.value = client1Value;
            eu.x_road.xsd.identifiers.XRoadServiceIdentifierType service1Value = null;
            service1.value = service1Value;
            java.lang.String id1Value = "";
            id1.value = id1Value;
            java.lang.String protocolVersion1Value = "";
            protocolVersion1.value = protocolVersion1Value;
            java.lang.String userId1Value = "";
            userId1.value = userId1Value;
            java.lang.String issue1Value = "";
            issue1.value = issue1Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
